config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "tags#search"
   
  root to: "pages#home"
  get '/about_us', to: "pages#about_us"
  get '/sign-up', to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :users, except: [:new]
  resources :templates
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :templates
    validates :name, presence: true, length: {minimum: 2, maximum: 100}

   

    end

app/models/template.rb
class Template < ApplicationRecord
    has_and_belongs_to_many :tags
    belongs_to :user
    has_one_attached :file, dependent: :destroy
    validates :title, presence: true, length: {minimum: 2, maximum: 100}
    validate :image_path_exists
    

    def image_path_exists
        require 'open-uri'

        begin
            path = URI.open(image_path)
            errors.add(:image_path, "does not contain image content") and return unless path.content_type.starts_with?("image")
            
        rescue 
            errors.add(:image_path, "invalid url")
            
        else
            
        end
    end

 
      
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, :email, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25}
    validates :email, format: {with: URI::MailTo::EMAIL_REGEXP}
    has_secure_password
    
    has_many :templates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def require_user

        if guest?
            flash[:notice] = "You must login first."
            redirect_to login_path
        end

    end

    def already_signed_in?
        if !guest?
            flash[:notice] = "You are already signed in."
            redirect_to templates_path
        end
    end

    def guest?
        !helpers.logged_in?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @templates = Template.all
    @tags = Tag.all

    
  end

  

  def show 
    @template = Template.find(params[:id])
    @tag = Tag.find(params[:id])

  end
  
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @q = Tag.ransack(params[:q])
    @tags = @q.result(distinct: true)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_signed_in?, except: [:destroy]
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Login successful"
      redirect_to templates_path
    else
      flash[:notice] = "Login failed"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logout Successful"
    redirect_to login_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]
  before_action :require_user

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  def search
    @tags = Tag.where("name LIKE ?", "%" + params[:q]+"%")
  end
  
  # GET /tags/1 or /tags/1.json
  def show
    @tag = Tag.find(params[:id])
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
    before_action :set_template, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show]
    before_action :require_same_user, only: [:destroy]


    def index
        @templates = Template.all
    end

    def new
        @template = Template.new
    end

    def create
        @template = helpers.current_user.templates.new(template_params)

        if @template.save
            flash[:notice] = "Template uploaded successfully."
            redirect_to templates_path
        else
            flash[:notice] = "Hmm...sorry is wrong. Please try again."
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @template = Template.find(params[:id])
    end

    def update
        @template = Template.find(params[:id])

        if @template.update(template_params)
            redirect_to templates_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def show
        @template = Template.find(params[:id])
    end

    def destroy
        @template = Template.find(params[:id])

        @template.destroy
        redirect_to templates_path
    end

    

    private
    def require_same_user
        if helpers.current_user != @template.current_user
            flash[:notice] = "Unauthorized!"
            redirect_to helpers.current_user
        end
    end

    def set_template
        @template = Template.find(params[:id])
    end
    
    def template_params
        params.require(:template).permit(:title, :image_path, :file, tag_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_signed_in?, only: [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:notice] = "Account created successfully"
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])

  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseProjectPptFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    
    <%= render 'shared/nav' %>
  
    
   

     <% if flash[:notice] %>
    <%= flash[:notice] %>
  <%end%>
    <%= yield %>
  </body>
</html>

app/views/layouts/dump.erb
before_action :set_query

    def search
        @tags = Tag.all
    
        if params[:search_by_name] && params[:search_by_name] != ""
          @tags = @tags.where("name like ?", 
          "%# {params[:search_by_name]}%")
        end
    end
    def set_query
        @q = Tag.ransack(params[:q])
        @tags = @q.result(distinct: true)
    end


    <% @tag.templates.each do |template| %>

  <%=template.title%>
  <%= image_tag template.image_path%>
<%end%>


<div>
  <%= link_to "Edit this tag", edit_tag_path(@tag) %> |
  <%= link_to "Back to tags", tags_path %>

  <%= button_to "Destroy this tag", @tag, method: :delete %>
</div>

app/views/pages/home.html.erb
<h1 class="text-center">Never Design a PowerPoint Again</h1>



<%= render 'shared/index'%>

app/views/search/_form.html.erb
<%= search_form_for(@q, class: 'd-flex') do |f| %>

    <%= f.label :name_cont %>
    <%= f.search_field :name_cont, placeholder: "Search tags...", class: "form-control me-2" %>
    
    <%= f.submit "Search!", class: "btn btn-outline-success" %>
<% end %>

app/views/shared/_form.html.erb
<%= form_tag "/tags", method: "GET" do %>
    <%= label_tag :search_by_name%>
    <%= text_field_tag :search_by_name, params[:search_by_name], class: "form-control me-2"%>

<%= submit_tag "Search",class: "btn btn-outline-success" %>
<% end %>

app/views/shared/_index.html.erb
<div class="container">


  <div class="row">
    <% @templates.limit(10).each do |template| %>
      <div class="col-xs-12.col-md-6.col-lg-4">
        <div class="card" style="width: 100%; margin-bottom: 1rem">
  
          <%= image_tag template.image_path, class: "card-img-top"%>
        <div class="card-body">
          <h5 class="card-title"><%= template.title %></h5>
          
          <p class="card-text"><%=template.user.username if template.user%></p>

          <% template.tags.each do |tag| %>
          <p class="card-text"><%=tag.name%></p>
          <%end%>
          
          
        
       
         
    
          <%= link_to "View this Template", template, class: "btn btn-primary" %>
    
        </div>
      </div>
  </div>
  <% end %>
</div>

</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <%= link_to "PowerPoint Finder", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if logged_in? %>

      <li class="nav-item active">
        <%= link_to "My Templates", user_path(current_user),  class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Upload a Template", new_template_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Tags', tags_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Logout', logout_path, data: {"turbo-method": :delete}, class: "nav-link" %>
      </li>
        
        
      
    
    <% else %>
    <li class="nav-item active">
        <%= link_to 'Sign Up', sign_up_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Login", login_path, class: "nav-link" %>
      </li>
     
    <% end %>
     </ul>
     <form class="form inline my-2 my-lg-0 margin-right" action="/search">
      <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search" aria-label="Search">
      <button class="bt btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
  
      
    
  </div>
</nav>

app/views/tags/_edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Name:</strong>
    <%= tag.name %>
  </p>

</div>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tags</h1>

<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>
    <p>
      <%= link_to "Show this tag", tag %>
    </p>
  <% end %>
</div>

<%= link_to "New tag", new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/search.erb
<h1>Search Results</h1>



<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>
    <p>
      <%= link_to "Show this tag", tag %>
    </p>
  <% end %>
</div>

app/views/tags/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tag %>

<div class="container">
  <div class="row">
    <% @tag.templates.each do |template| %>
      <div class="col-xs-12.col-md-6.col-lg-4">
        <div class="card" style="width: 100%; margin-bottom: 1rem">
  
          <%= image_tag template.image_path, class: "card-img-top"%>
        <div class="card-body">
          <h5 class="card-title"><%= template.title %></h5>
          
          <p class="card-text"><%=template.user.username if template.user%></p>

          <% template.tags.each do |tag| %>
          <p class="card-text"><%=tag.name%></p>
          <%end%>     
         
    
          <%= link_to "View this Template", template, class: "btn btn-primary" %>
          <%= link_to "Edit this tag", edit_tag_path(@tag), class: "btn btn-primary" %> |
          <%= link_to "Back to tags", tags_path, class: "btn btn-primary" %>
    
        </div>
      </div>
  </div>
  <% end %>
</div>
</div>

app/views/templates/_attachment.html.erb
<% if template.file.attached? %>
    <div class="row">
        <%= button_to template.file.filename, url_for(template.file), class: "btn btn-primary" %>
<% end %>

app/views/templates/edit.html.erb
<h1>Edit <% @template.title%> </h1>

<%= form_with(model: @template) do |form| %>
    <% if @template.errors.any? %>
        <% @template.errors.full_messages.each do |message| %>
            <div>
                <%= message %>
            </div>
            <% end %>
        <% end %>
        <div>
            <%= form.label :title %>
            <%= form.text_field :title %>
        </div>
        <div>
            <%= form.label :image_path %>
            <%= form.text_field :image_path %>
        </div>
        <div>
        <%= form.label :file, style: "display: block" %>
        <%= form.file_field :file %>
        </div>
    <%= form.submit :"Update" %>
<% end %>

app/views/templates/index.html.erb
<h1 class="text-center">Never Design a PowerPoint Again</h1>

<%= render 'shared/index' %>

app/views/templates/new.html.erb
<h1>Upload a PowerPoint Template</h1>
<%= form_with(model: @template) do |form| %>
<% if @template.errors.any? %>
        <% @template.errors.full_messages.each do |message| %>
            <div>
                <%= message %>
            </div>
            <% end %>
        <% end %>
    
        <div>
            <%= form.label :title %>
            <%= form.text_field :title %>
        </div>
        <div>
            <%= form.label :image_path %>
            <%= form.text_field :image_path %>
        </div>
        <%= form.label :tag_id %>
        <%= form.collection_select(:tag_ids, Tag.all, :id, :name, {}, {multiple:true}) %>

        <%= form.label :tag_id %>
        <%= form.text_field :tag_ids %>

        <%= form.label :file, style: "display: block" %>
        <%= form.file_field :file %>


    <%= form.submit :"Upload" %>

<% end %>

app/views/templates/show.cc.html.erb
<h1><%= @template.title %></h1>

<% if @template.user%>
    <div><%= link_to "By: #{@template.user.username}", @template.user %></div>
<% end %>
<div>
    <%= image_tag @template.image_path, style: "border: 1px solid black" %>

</div>

<div>
    <% @template.tags.each do |tag| %>
        <b style="margin-right: 6px"><%=tag.name%></b>
    <%end %>
</div>

<%= render 'templates/attachment', template: @template%>
<%= link_to "Edit", edit_template_path(@template)%>

<% if current_user == @template.user %>

    <%= button_to "Destroy", @template, method: :delete %>
<%end %>

app/views/templates/show.html.erb
<div class="container">
  <div class="row">
     <div class="col-xs-12.col-md-6.col-lg-4">
        <div class="card" style="width: 100%; margin-bottom: 1rem">
  
          <%= image_tag @template.image_path, class: "card-img-top"%>
            <div class="card-body">
            <h5 class="card-title"><%= @template.title %></h5>

          <% if @template.user%>
           <p class="card-text"><%= link_to "By: #{@template.user.username}", @template.user %></p>
            <% end %>
          
          <% @template.tags.each do |tag| %>
          <p class="card-text"><%=tag.name%></p>
          <%end%>     

 
    
          <%= link_to "Edit this Template", edit_template_path(@template), class: "btn btn-primary" %>

          <%= render 'templates/attachment', template: @template, class: "btn btn-primary"%>
          
      

          <% if current_user == @template.user %>
            <%= button_to "Delete", @template, method: :delete, class:"btn btn-danger", style: "float-right" %>
          <%end %>

          <%= link_to "Back to templates", templates_path, class: "btn btn-primary" %>
    
        </div>
      </div>
  </div>
 
</div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_with(model: @user) do |form| %>
    <div>
        <%= form.label :username %>
        <%= form.text_field :username %>
    </div>
    <div>
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>
    <div>
        <%= form.label :password %>
        <%= form.text_field :password %>
    </div>
    <%= form.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>PowerPoint Templates</h1>


 
 <h3 style="color: blue"><%= @user.username %></h3>   


<div class="container">


  <div class="row">
    <% @user.templates.each do |template| %>
      <div class="col-xs-12.col-md-6.col-lg-4">
        <div class="card" style="width: 100%; margin-bottom: 1rem">
  
          <%= image_tag template.image_path, class: "card-img-top"%>
        <div class="card-body">
          <h5 class="card-title"><%= template.title %></h5>
          
          

          <% template.tags.each do |tag| %>
          <p class="card-text"><%=tag.name%></p>
          <%end%>
          
          
        
       
         
    
          <%= link_to "Show", template_path(template), class: "btn btn-primary" %>
    
        </div>
      </div>
  </div>
  <% end %>
</div>

</div>